
services:
  nodeapp:
    image: abedalgane99/dockerpractice
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 5
      update_config:
        parallelism: 2      
        delay: 10s          
        failure_action: pause
        order: start-first
    volumes:
      - ./src:/app/src:ro
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    depends_on:
      - nodeapp

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - nodeapp

  web:
    image: nginx
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
    depends_on:
      - nodeapp


      

  redis:
    image: redis
    depends_on:
      - nodeapp
volumes:
  mongo-db: